-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_pdts_tlu_io is

  constant IPBUS_SEL_WIDTH: positive := 3;
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_pdts_tlu_io(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Fri Nov 27 14:18:46 2020 
  constant N_SLV_CSR: integer := 0;
  constant N_SLV_CONFIG: integer := 1;
  constant N_SLV_I2C: integer := 2;
  constant N_SLV_FREQ: integer := 3;
  constant N_SLAVES: integer := 4;
-- END automatically generated VHDL

    
end ipbus_decode_pdts_tlu_io;

package body ipbus_decode_pdts_tlu_io is

  function ipbus_sel_pdts_tlu_io(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Fri Nov 27 14:18:46 2020 
    if    std_match(addr, "--------------------------0-0-0-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- csr / base 0x00000000 / mask 0x0000002a
    elsif std_match(addr, "--------------------------0-0-1-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CONFIG, IPBUS_SEL_WIDTH)); -- config / base 0x00000002 / mask 0x0000002a
    elsif std_match(addr, "--------------------------0-1---") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_I2C, IPBUS_SEL_WIDTH)); -- i2c / base 0x00000008 / mask 0x00000028
    elsif std_match(addr, "--------------------------1-0-0-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_FREQ, IPBUS_SEL_WIDTH)); -- freq / base 0x00000020 / mask 0x0000002a
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_pdts_tlu_io;

end ipbus_decode_pdts_tlu_io;

