set_property BITSTREAM.Config.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

# For 312.5MHz bit rate
create_clock -period 3.200 -name clk_bp  [get_ports clk_bp_p]
create_clock -period 3.200 -name clk_pll [get_ports clk_pll_p]
create_clock -period 3.200 -name clk_cdr [get_ports clk_cdr_p]

# For 312.5MHz bit rate
# create_clock -period 3.200 -name fmc_clk [get_ports fmc_clk_p]
# create_clock -period 3.200 -name rec_clk [get_ports rec_clk_p]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks clk_bp] -group [get_clocks -include_generated_clocks clk_pll] -group [get_clocks -include_generated_clocks clk_cdr] -group [get_clocks -include_generated_clocks -of_obj [get_pins -of_obj [get_cells infra/clocks/mmcm] -filter {NAME =~ *CLKOUT*}]]

set_property IOSTANDARD LVDS_25 [get_port {clk_bp_* clk_pll_* clk_cdr_* d_bp_* d_sfp_p[*] d_sfp_n[*] d_cdr_* q_bp_* q_sfp_p[*] q_sfp_n[*]}]
set_property DIFF_TERM TRUE [get_port {clk_bp_* clk_pll_* clk_cdr_* d_bp_* d_sfp_p[*] d_sfp_n[*] d_cdr_* q_bp_* q_sfp_p[*] q_sfp_n[*]}]

set_property PACKAGE_PIN G5 [get_ports {clk_bp_p}]
set_property PACKAGE_PIN G4 [get_ports {clk_bp_n}]
set_property PACKAGE_PIN P5 [get_ports {clk_pll_p}]
set_property PACKAGE_PIN N4 [get_ports {clk_pll_n}]
set_property PACKAGE_PIN H7 [get_ports {clk_cdr_p}]
set_property PACKAGE_PIN H6 [get_ports {clk_cdr_n}]
set_property PACKAGE_PIN Y30 [get_ports {d_bp_p}]
set_property PACKAGE_PIN Y31 [get_ports {d_bp_n}]
set_property PACKAGE_PIN H1 [get_ports {d_sfp_p[0]}]
set_property PACKAGE_PIN G1 [get_ports {d_sfp_n[0]}]
set_property PACKAGE_PIN T8 [get_ports {d_sfp_p[1]}]
set_property PACKAGE_PIN T7 [get_ports {d_sfp_n[1]}]
set_property PACKAGE_PIN N1 [get_ports {d_sfp_p[2]}]
set_property PACKAGE_PIN M1 [get_ports {d_sfp_n[2]}]
set_property PACKAGE_PIN F3 [get_ports {d_sfp_p[3]}]
set_property PACKAGE_PIN F2 [get_ports {d_sfp_n[3]}]
set_property PACKAGE_PIN K7 [get_ports {d_cdr_p}]
set_property PACKAGE_PIN K6 [get_ports {d_cdr_n}]
set_property PACKAGE_PIN R6 [get_ports {q_bp_p}]
set_property PACKAGE_PIN R5 [get_ports {q_bp_n}]
set_property PACKAGE_PIN G7 [get_ports {q_sfp_p[0]}]
set_property PACKAGE_PIN G6 [get_ports {q_sfp_n[0]}]
set_property PACKAGE_PIN K1 [get_ports {q_sfp_p[1]}]
set_property PACKAGE_PIN J1 [get_ports {q_sfp_n[1]}]
set_property PACKAGE_PIN K3 [get_ports {q_sfp_p[2]}]
set_property PACKAGE_PIN K2 [get_ports {q_sfp_n[2]}]
set_property PACKAGE_PIN M2 [get_ports {q_sfp_p[3]}]
set_property PACKAGE_PIN L2 [get_ports {q_sfp_n[3]}]
set_property PACKAGE_PIN K11 [get_ports {q_sfp_p[4]}]
set_property PACKAGE_PIN J11 [get_ports {q_sfp_n[4]}]
set_property PACKAGE_PIN U5 [get_ports {q_sfp_p[5]}]
set_property PACKAGE_PIN U4 [get_ports {q_sfp_n[5]}]
set_property PACKAGE_PIN M7 [get_ports {q_sfp_p[6]}]
set_property PACKAGE_PIN M6 [get_ports {q_sfp_n[6]}]
set_property PACKAGE_PIN M11 [get_ports {q_sfp_p[7]}]
set_property PACKAGE_PIN M10 [get_ports {q_sfp_n[7]}]
false_path {d_bp_* d_sfp_p[*] d_sfp_n[*] d_cdr_* q_bp_* q_sfp_p[*] q_sfp_n[*]} eth_refclk


set_property IOSTANDARD LVCMOS25 [get_port {inmux[*] rstb_i2c scl sda sfp_scl[*] sfp_sda[*] pll_rstn}]
set_property PACKAGE_PIN R3 [get_ports {inmux[0]}]
set_property PACKAGE_PIN J6 [get_ports {inmux[1]}]
set_property PACKAGE_PIN R2 [get_ports {inmux[2]}]
set_property PACKAGE_PIN J5 [get_ports {rstb_i2c}]
set_property PACKAGE_PIN P6 [get_ports {scl}]
set_property PACKAGE_PIN R11 [get_ports {sda}]
set_property PACKAGE_PIN K5 [get_ports {sfp_scl[0]}]
set_property PACKAGE_PIN L5 [get_ports {sfp_sda[0]}]
set_property PACKAGE_PIN K8 [get_ports {sfp_scl[1]}]
set_property PACKAGE_PIN L8 [get_ports {sfp_sda[1]}]
set_property PACKAGE_PIN G2 [get_ports {sfp_scl[2]}]
set_property PACKAGE_PIN H2 [get_ports {sfp_sda[2]}]
set_property PACKAGE_PIN U6 [get_ports {sfp_scl[3]}]
set_property PACKAGE_PIN U7 [get_ports {sfp_sda[3]}]
set_property PACKAGE_PIN H8 [get_ports {sfp_scl[4]}]
set_property PACKAGE_PIN H9 [get_ports {sfp_sda[4]}]
set_property PACKAGE_PIN J3 [get_ports {sfp_scl[5]}]
set_property PACKAGE_PIN J4 [get_ports {sfp_sda[5]}]
set_property PACKAGE_PIN P3 [get_ports {sfp_scl[6]}]
set_property PACKAGE_PIN P4 [get_ports {sfp_sda[6]}]
set_property PACKAGE_PIN U1 [get_ports {sfp_scl[7]}]
set_property PACKAGE_PIN U2 [get_ports {sfp_sda[7]}]

set_property PACKAGE_PIN P9 [get_ports {pll_rstn}]

false_path {inmux[*] rstb_i2c scl sda sfp_scl[*] sfp_sda[*] pll_rstn} eth_refclk

