set_property BITSTREAM.Config.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

# For 312.5MHz bit rate
create_clock -period 3.200 -name clk [get_ports clk_p]
create_clock -period 3.200 -name clk_cdr [get_ports clk_cdr_p]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks clk] -group [get_clocks -include_generated_clocks clk_cdr] -group [get_clocks -include_generated_clocks -of_obj [get_pins -of_obj [get_cells infra/clocks/mmcm] -filter {NAME =~ *CLKOUT*}]]

set_property IOSTANDARD LVDS_25 [get_port {clk_p clk_n d_p[*] d_n[*] q_p q_n d_cdr_* clk_cdr_* d_hdmi_* q_hdmi_* d_usfp_* q_usfp_* gpio_*}]
set_property DIFF_TERM TRUE [get_port {clk_p clk_n d_p[*] d_n[*] d_cdr_* clk_cdr_* d_hdmi_* d_usfp_*}]
set_property PACKAGE_PIN N5 [get_ports {clk_p}]
set_property PACKAGE_PIN P5 [get_ports {clk_n}]
set_property PACKAGE_PIN U1 [get_ports {d_p[0]}]
set_property PACKAGE_PIN V1 [get_ports {d_n[0]}]
set_property PACKAGE_PIN K5 [get_ports {d_p[1]}]
set_property PACKAGE_PIN L4 [get_ports {d_n[1]}]
set_property PACKAGE_PIN G4 [get_ports {d_p[2]}]
set_property PACKAGE_PIN G3 [get_ports {d_n[2]}]
set_property PACKAGE_PIN C2 [get_ports {d_p[3]}]
set_property PACKAGE_PIN C1 [get_ports {d_n[3]}]
set_property PACKAGE_PIN G6 [get_ports {d_p[4]}]
set_property PACKAGE_PIN F6 [get_ports {d_n[4]}]
set_property PACKAGE_PIN J4 [get_ports {d_p[5]}]
set_property PACKAGE_PIN H4 [get_ports {d_n[5]}]
set_property PACKAGE_PIN K2 [get_ports {d_p[6]}]
set_property PACKAGE_PIN K1 [get_ports {d_n[6]}]
set_property PACKAGE_PIN B1 [get_ports {d_p[7]}]
set_property PACKAGE_PIN A1 [get_ports {d_n[7]}]
set_property PACKAGE_PIN L6 [get_ports {q_p}]
set_property PACKAGE_PIN L5 [get_ports {q_n}]
set_property PACKAGE_PIN R6 [get_ports {d_cdr_p}]
set_property PACKAGE_PIN R5 [get_ports {d_cdr_n}]
set_property PACKAGE_PIN E3 [get_ports {clk_cdr_p}]
set_property PACKAGE_PIN D3 [get_ports {clk_cdr_n}]
set_property PACKAGE_PIN C4 [get_ports {d_hdmi_p}]
set_property PACKAGE_PIN B4 [get_ports {d_hdmi_n}]
set_property PACKAGE_PIN M6 [get_ports {q_hdmi_p}]
set_property PACKAGE_PIN N6 [get_ports {q_hdmi_n}]
set_property PACKAGE_PIN M3 [get_ports {d_usfp_p}]
set_property PACKAGE_PIN M2 [get_ports {d_usfp_n}]
set_property PACKAGE_PIN L1 [get_ports {q_usfp_p}]
set_property PACKAGE_PIN M1 [get_ports {q_usfp_n}]
set_property PACKAGE_PIN P4 [get_ports {gpio_p[0]}]
set_property PACKAGE_PIN P3 [get_ports {gpio_n[0]}]
set_property PACKAGE_PIN P2 [get_ports {gpio_p[1]}]
set_property PACKAGE_PIN R2 [get_ports {gpio_n[1]}]
set_property PACKAGE_PIN U4 [get_ports {gpio_p[2]}]
set_property PACKAGE_PIN U3 [get_ports {gpio_n[2]}]
false_path {d_p[*] d_n[*] q_p q_n d_cdr_* d_hdmi_* q_hdmi_* d_usfp_* q_usfp_* gpio_*} osc_clk

set_property IOSTANDARD LVCMOS25 [get_port {rstb_clk clk_lolb sfp_los[*] cdr_los cdr_lol inmux[*] rstb_i2cmux usfp_* ucdr_* ledb[*] scl sda rstb_i2c}]
set_property PACKAGE_PIN T6 [get_ports {rstb_clk}]
set_property PACKAGE_PIN K3 [get_ports {clk_lolb}]
set_property PACKAGE_PIN R8 [get_ports {sfp_los[0]}]
set_property PACKAGE_PIN T8 [get_ports {sfp_los[1]}]
set_property PACKAGE_PIN E2 [get_ports {sfp_los[2]}]
set_property PACKAGE_PIN D2 [get_ports {sfp_los[3]}]
set_property PACKAGE_PIN J3 [get_ports {sfp_los[4]}]
set_property PACKAGE_PIN J2 [get_ports {sfp_los[5]}]
set_property PACKAGE_PIN M4 [get_ports {sfp_los[6]}]
set_property PACKAGE_PIN N4 [get_ports {sfp_los[7]}]
set_property PACKAGE_PIN C6 [get_ports {cdr_los}]
set_property PACKAGE_PIN C5 [get_ports {cdr_lol}]
set_property PACKAGE_PIN N2 [get_ports {inmux[0]}]
set_property PACKAGE_PIN N1 [get_ports {inmux[1]}]
set_property PACKAGE_PIN R1 [get_ports {inmux[2]}]
set_property PACKAGE_PIN T1 [get_ports {rstb_i2cmux}]
set_property PACKAGE_PIN L3 [get_ports {usfp_fault}]
set_property PACKAGE_PIN F1 [get_ports {usfp_los}]
set_property PACKAGE_PIN E1 [get_ports {usfp_txdis}]
set_property PACKAGE_PIN H2 [get_ports {usfp_sda}]
set_property PACKAGE_PIN G2 [get_ports {usfp_scl}]
set_property PACKAGE_PIN F4 [get_ports {ucdr_los}]
set_property PACKAGE_PIN F3 [get_ports {ucdr_lol}]
set_property PACKAGE_PIN E7 [get_ports {ledb[0]}]
set_property PACKAGE_PIN H6 [get_ports {ledb[1]}]
set_property PACKAGE_PIN H1 [get_ports {ledb[2]}]
set_property PACKAGE_PIN N17 [get_ports {scl}]
set_property PACKAGE_PIN P18 [get_ports {sda}]
set_property PACKAGE_PIN R7 [get_ports {rstb_i2c}]
false_path {rstb_clk clk_lolb sfp_los[*] cdr_los cdr_lol inmux[*] rstb_i2cmux usfp_* ucdr_* ledb[*] scl sda rstb_i2c} osc_clk
