# For 312.5MHz bit rate
create_clock -period 3.200 -name fmc_clk [get_ports fmc_clk_p]
create_clock -period 3.200 -name rec_clk [get_ports rec_clk_p]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks fmc_clk] -group [get_clocks -include_generated_clocks rec_clk] -group [get_clocks -include_generated_clocks -of_obj [get_pins -of_obj [get_cells infra/clocks/mmcm] -filter {NAME =~ *CLKOUT*}]]

set_property IOSTANDARD LVDS_25 [get_port {fmc_clk_* rec_clk_* rec_d_* clk_out_* rj45_din_* rj45_dout_* sfp_dout_* gpin_* gpout_*}]
set_property DIFF_TERM TRUE [get_port {fmc_clk_* rec_clk_* rec_d_* rj45_din_* gpin_*}]
set_property PACKAGE_PIN AF22 [get_ports {fmc_clk_p}]
set_property PACKAGE_PIN AG23 [get_ports {fmc_clk_n}]
set_property PACKAGE_PIN AG29 [get_ports {rec_clk_p}]
set_property PACKAGE_PIN AH29 [get_ports {rec_clk_n}]
set_property PACKAGE_PIN AG22 [get_ports {rec_d_p}]
set_property PACKAGE_PIN AH22 [get_ports {rec_d_n}]
set_property PACKAGE_PIN AD23 [get_ports {clk_out_p}]
set_property PACKAGE_PIN AE24 [get_ports {clk_out_n}]
set_property PACKAGE_PIN AC22 [get_ports {rj45_din_p}]
set_property PACKAGE_PIN AD22 [get_ports {rj45_din_n}]
set_property PACKAGE_PIN AG30 [get_ports {rj45_dout_p}]
set_property PACKAGE_PIN AH30 [get_ports {rj45_dout_n}]
set_property PACKAGE_PIN AF26 [get_ports {sfp_dout_p}]
set_property PACKAGE_PIN AF27 [get_ports {sfp_dout_n}]
set_property PACKAGE_PIN AK20 [get_ports {gpin_0_p}]
set_property PACKAGE_PIN AK21 [get_ports {gpin_0_n}]
set_property PACKAGE_PIN AG20 [get_ports {gpout_0_p}]
set_property PACKAGE_PIN AH20 [get_ports {gpout_0_n}]
set_property PACKAGE_PIN AF20 [get_ports {gpout_1_p}]
set_property PACKAGE_PIN AF21	[get_ports {gpout_1_n}]
false_path {rec_d_* clk_out_* rj45_din_* rj45_dout_* sfp_dout_* gpin_* gpout_*} osc_clk

set_property IOSTANDARD LVCMOS25 [get_port {pll_rstn cdr_lol cdr_los sfp_los sfp_tx_dis sfp_flt uid_scl uid_sda sfp_scl sfp_sda pll_scl pll_sda}]
set_property PACKAGE_PIN AJ22 [get_ports {cdr_lol}]
set_property PACKAGE_PIN AJ23 [get_ports {cdr_los}]
set_property PACKAGE_PIN AK23 [get_ports {sfp_los}]
set_property PACKAGE_PIN AB24 [get_ports {sfp_tx_dis}]
set_property PACKAGE_PIN AC25 [get_ports {sfp_flt}]
set_property PACKAGE_PIN K21 [get_ports {uid_scl}]
set_property PACKAGE_PIN L21 [get_ports {uid_sda}]
set_property PACKAGE_PIN AG25 [get_ports {sfp_scl}]
set_property PACKAGE_PIN AH25 [get_ports {sfp_sda}]
set_property PACKAGE_PIN AE25 [get_ports {pll_scl}]
set_property PACKAGE_PIN AF25 [get_ports {pll_sda}]
set_property PACKAGE_PIN AE28 [get_ports {pll_rstn}]
false_path {pll_rstn cdr_lol cdr_los sfp_los sfp_tx_dis sfp_flt uid_scl uid_sda sfp_scl sfp_sda pll_scl pll_sda} osc_clk
