set_property BITSTREAM.Config.SPI_BUSWIDTH 4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]

# For 312.5MHz bit rate
create_clock -period 3.200 -name fmc_clk [get_ports fmc_clk_p]
create_clock -period 3.200 -name rec_clk [get_ports rec_clk_p]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks fmc_clk] -group [get_clocks -include_generated_clocks rec_clk] -group [get_clocks -include_generated_clocks -of_obj [get_pins -of_obj [get_cells infra/clocks/mmcm] -filter {NAME =~ *CLKOUT*}]]

set_property IOSTANDARD LVDS_25 [get_port {fmc_clk_* rec_clk_* rec_d_* clk_out_* rj45_din_* rj45_dout_* sfp_dout_* gpin_* gpout_*}]
set_property DIFF_TERM TRUE [get_port {fmc_clk_* rec_clk_* rec_d_* rj45_din_* gpin_*}]
set_property PACKAGE_PIN V4 [get_ports {fmc_clk_p}]
set_property PACKAGE_PIN W4 [get_ports {fmc_clk_n}]
set_property PACKAGE_PIN R4 [get_ports {rec_clk_p}]
set_property PACKAGE_PIN T4 [get_ports {rec_clk_n}]
set_property PACKAGE_PIN M3 [get_ports {rec_d_p}]
set_property PACKAGE_PIN M2 [get_ports {rec_d_n}]
set_property PACKAGE_PIN T5 [get_ports {clk_out_p}]
set_property PACKAGE_PIN U5 [get_ports {clk_out_n}]
set_property PACKAGE_PIN U2 [get_ports {rj45_din_p}]
set_property PACKAGE_PIN V2 [get_ports {rj45_din_n}]
set_property PACKAGE_PIN G1 [get_ports {rj45_dout_p}]
set_property PACKAGE_PIN F1 [get_ports {rj45_dout_n}]
set_property PACKAGE_PIN W6 [get_ports {sfp_dout_p}]
set_property PACKAGE_PIN W5 [get_ports {sfp_dout_n}]
set_property PACKAGE_PIN AB3 [get_ports {gpin_0_p}]
set_property PACKAGE_PIN AB2 [get_ports {gpin_0_n}]
set_property PACKAGE_PIN H2 [get_ports {gpout_0_p}]
set_property PACKAGE_PIN G2 [get_ports {gpout_0_n}]
set_property PACKAGE_PIN L3 [get_ports {gpout_1_p}]
set_property PACKAGE_PIN K3 [get_ports {gpout_1_n}]
false_path {rec_d_* clk_out_* rj45_din_* rj45_dout_* sfp_dout_* gpin_* gpout_*} eth_refclk

set_property IOSTANDARD LVCMOS25 [get_port {pll_rstn cdr_lol cdr_los  sfp_flt uid_scl uid_sda sfp_scl sfp_sda pll_scl pll_sda}]
set_property PACKAGE_PIN K2 [get_ports {cdr_lol}]
set_property PACKAGE_PIN J2 [get_ports {cdr_los}]
#set_property PACKAGE_PIN R3 [get_ports {sfp_los}]
#set_property PACKAGE_PIN Y3 [get_ports {sfp_tx_disable}]
set_property PACKAGE_PIN AA3 [get_ports {sfp_flt}]
set_property PACKAGE_PIN AB21 [get_ports {uid_scl}]
set_property PACKAGE_PIN AB22 [get_ports {uid_sda}]
set_property PACKAGE_PIN W1 [get_ports {sfp_scl}]
set_property PACKAGE_PIN Y1 [get_ports {sfp_sda}]
set_property PACKAGE_PIN T1 [get_ports {pll_scl}]
set_property PACKAGE_PIN U1 [get_ports {pll_sda}]
set_property PACKAGE_PIN V9 [get_ports {pll_rstn}]
false_path {pll_rstn cdr_lol cdr_los  sfp_flt uid_scl uid_sda sfp_scl sfp_sda pll_scl pll_sda} eth_refclk
